### ISSUE TITLE
Speed up CI builds by analysing diffs

### ISSUE THREAD

**Issue by gampleman** [rtfeldman/node-test-runner#111]
Inspired by [flake8](http://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8--diff), I think it would be cool to have a `--with-diff` option that would allow accepting a git diff and working out from that diff what tests could be affected by the changes in the diff which tests it is necessary to run.

I think the simplest solution would be built on top of #110 with the following assumptions:

- the branch that is being diffed against is a safe branch where the build is already green (i.e. `master` where you only merge if tests pass).
- only file names would be taken from the diff. So no need to worry about the contents of what changed in the file (that would be cool, but much more complicated)

A travis configuration would then look something like this:

```yaml
sudo: false

cache:
  directories:
    - elm-stuff/build-artifacts
    - elm-stuff/packages
    - sysconfcpus
os:
  - linux

env:
  matrix:
    - ELM_VERSION=0.18.0 TARGET_NODE_VERSION=node

before_install:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

install:
  - nvm install $TARGET_NODE_VERSION
  - nvm use $TARGET_NODE_VERSION
  - node --version
  - npm --version
  - npm install -g elm@$ELM_VERSION elm-test
  - git clone https://github.com/NoRedInk/elm-ops-tooling
  - elm-ops-tooling/with_retry.rb elm package install --yes
  # Faster compile on Travis.
  - |
    if [ ! -d sysconfcpus/bin ];
    then
      git clone https://github.com/obmarg/libsysconfcpus.git;
      cd libsysconfcpus;
      ./configure --prefix=$TRAVIS_BUILD_DIR/sysconfcpus;
      make && make install;
      cd ..;
    fi
before_script:
  - $TRAVIS_BUILD_DIR/sysconfcpus/bin/sysconfcpus -n 2 elm-make ./tests/Main.elm

script:
  -  git diff -u $TRAVIS_COMMIT_RANGE | elm test --with-diff
```
